Fix OS image update not detected for versions without suffix..
metal-stack/firewall-controller-manager pull request #43
Opened 2023-08-31 11:42 UTC by Gerrit91

2023-09-01 07:43 UTC, Gerrit91 commented on controllers/deployment/reconcile.go
> +	image, err := m.Image().FindLatestImage(image.NewFindLatestImageParams().WithID(newS.Image).WithContext(ctx), nil)
Yes, this would be good addition.

2023-09-04 11:58 UTC, majst01 commented
Deployment does not change and therefor the imagecache will not be asked to fetch the newest image.

It should depend on the gardener `maintain` reconciliation and trigger firewall roll during the maintenance window

2024-05-02 14:34 UTC, Gerrit91 commented
Looks like this finally works now.

2024-05-03 12:53 UTC, majst01 requested changes

2024-05-03 12:53 UTC, majst01 commented on controllers/deployment/controller.go
> +		imageCache: cache.New(5*time.Minute, func(ctx context.Context, id string) (*models.V1ImageResponse, error) {
every 5 minute is brutal when we release new versions of images ever 3-4 weeks.

2024-05-29 12:12 UTC, majst01 approved these changes

2024-05-29 13:13 UTC, merged